"""
Runnable demonstration of the assembler.

Run from the repo root:

    python 07-instructions/demo.py

Assembles two example programs from the programs/ folder into machine code,
shows the generated bytes next to the source, and runs them on the module-06 CPU
to prove the toolchain works end to end: text -> bytes -> execution.
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_REPO_ROOT, "06-cpu"))
sys.path.insert(0, _HERE)

from cpu import CPU, OPCODE_NAMES  # noqa: E402
from assembler import assemble_file  # noqa: E402


def disassemble(word: int) -> str:
    return f"{OPCODE_NAMES.get(word >> 4, 'DB?'):5} {word & 0xF}"


def show_assembly(name, path):
    print("=" * 60)
    print(f"ASSEMBLE  {name}")
    print("=" * 60)
    code = assemble_file(path)
    print("  addr  byte   disassembled")
    print("  ----------------------------")
    for addr, word in enumerate(code):
        print(f"   [{addr:2}]  {word:#04x}   {disassemble(word)}")
    return code


def main() -> None:
    # --- sum 1..5: check the final memory value ---
    sum_code = show_assembly("sum.asm", os.path.join(_HERE, "programs", "sum.asm"))
    cpu = CPU(sum_code)
    cpu.run()
    result = cpu.memory_dump()[15]  # SUM lives at address 15
    print(f"\n  Ran on the CPU -> SUM (memory[15]) = {result}  "
          f"(expected 15)\n")

    # --- countdown: check the OUT log ---
    cd_code = show_assembly("countdown.asm",
                            os.path.join(_HERE, "programs", "countdown.asm"))
    cpu2 = CPU(cd_code)
    cpu2.run()
    print(f"\n  Ran on the CPU -> OUT log = {cpu2.output}  (expected [3, 2, 1])")

    print("\n" + "=" * 60)
    print("Text -> machine code -> execution: the toolchain works.")
    print("=" * 60)


if __name__ == "__main__":
    main()
